### ISSUE TITLE
Lava Player is not playing local sounds

### ISSUE THREAD

**Issue by ArchangelX360** [ArchangelX360/dadigel-sounds#1]

**Comment by joffrey-bion** [comment]
Maybe it's a file permissions issue.

One thing we could try is serve the mp3 files via a web server as static files 😄 
That could at least show whether the problem lies in the local file access or the actual mp3 decoding/playback.

**Comment by ArchangelX360** [comment]
Fixed by https://github.com/ArchangelX360/dadigel-sounds/commit/64333d1bc0667a58529335a14307a1b4f7b1ea67
